default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: users_crud_development

test:
  <<: *default
  database: users_crud_test

production:
  <<: *default
  database: users_crud_production
  username: users_crud
  password: <%= ENV['USERS_CRUD_DATABASE_PASSWORD'] %>
